flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- JuicyPixels-3.2.7.2
- QuickCheck-2.9.1
- aeson-1.0.0.0
- ansi-terminal-0.6.2.3
- async-2.1.0
- attoparsec-0.13.0.2
- base-compat-0.9.1
- dlist-0.8.0.1
- hashable-1.2.4.0
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- mtl-2.2.1
- primitive-0.6.1.0
- quickcheck-io-0.1.3
- random-1.1
- scientific-0.3.4.9
- setenv-0.1.1.3
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.1
- tf-random-0.5
- time-locale-compat-0.1.1.3
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- zlib-0.6.1.1
resolver: lts-7.18
